language: ruby
rvm:
  - 2.2
before_script:
  - npm install -g gulp
before_install:
  - npm install -g npm@latest
install:
  - nvm install node
  - nvm use node
  - nvm alias default node
  - gem install github-pages
  - npm install
script: bash ./deploy.sh
branches:
  only:
  - staging
env:
  global:
  - ENCRYPTION_LABEL: "6315171ce8db"
  - COMMIT_AUTHOR_EMAIL: "it@cfms.org"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  - JEKYLL_ENV: "production"
cache:
  bundler: true
  directories:
    - node_modules
